modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "https://github.com/SaltSouls/Let-Me-Sleep/issues"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    displayURL = "https://github.com/SaltSouls/Let-Me-Sleep"
    updateJSONURL = "https://modrinth.com/mod/let-me-sleep"
    logoFile = "banner.png"
    authors = "${mod_authors}"
    credits = "${mod_credits}"
    description = '''${mod_description}'''
# Catalogue compat
    [modproperties."${mod_id}"]
    catalogueImageIcon="icon.png"
    catalogueBackground="background.png"

[[dependencies."${mod_id}"]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    ide = "BOTH"
[[dependencies."${mod_id}"]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"